version: '3.4'

services:
  surveytesting.apilayer:
    image: ${DOCKER_REGISTRY-}surveytestingapilayer
    build:
      context: .
      dockerfile: SurveyTesting.ApiLayer/Dockerfile
    environment:
      - DB_CS=Host=db;Port=5432;Database=SurveyTesting;Username=postgres;Password=1234567
    volumes:
      - ./logs:/app/logs
    ports:
      - "23627:8080"
      - "23628:8081"
    networks:
      - test-network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=SurveyTesting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
    networks:
      - test-network


networks:
  test-network:
    external: true