CREATE USER postgres WITH PASSWORD '1234567';

CREATE DATABASE SurveyTesting
OWNER = postgres
ENCODING = 'UTF8'
TABLESPACE = pg_default
CONNECTION LIMIT = -1;

GRANT ALL PRIVILEGES ON DATABASE SurveyTesting TO postgres;